#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/hasan/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
mpd &
xset -b &
redshift &
numlockx on &
autocutsel -fork &
tint2 &
/home/hasan/.config/transmissionauto.sh &
fbsetbg ~/Belgeler/Wallpapers/new/1436313049294.jpg
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/hasan/.fluxbox/log"
