#!/bin/bash

hc() {
    herbstclient "$@"
}


hc emit_hook reload
hc keyunbind --all

feh --bg-scale /home/hasan/Belgeler/Wallpapers/old/1418441627573.jpg

~/.config/herbstluftwm/bindings.sh

~/.config/herbstluftwm/decorations.sh

~/.config/herbstluftwm/rules.sh

panel=~/.config/herbstluftwm/panel2.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
	 start it on each monitor
    "$panel" $monitor &
done


urxvtd &
mpd &
xset -b &
redshift &
numlockx on &
autocutsel -fork &
transmission-daemon -f -c /home/hasan/İndirilenler/ &
~/.config/herbstluftwm/dzen.sh 
